version: '3'

services:
  gateway:
    container_name: gateway_
    restart: always
    build: ./gateway
    ports:
      - "8000:8000"

  character:
    container_name: character_
    restart: always
    build: ./characters
    ports:
      - "8001:8001"

  film:
    container_name: film_
    restart: always
    build: ./films
    ports:
      - "8002:8002"

  planet:
    container_name: planet_
    restart: always
    build: ./planets
    ports:
      - "8003:8003"
  
  database:
    container_name: database_
    restart: always
    build: ./database
    ports:
      - "8004:8004"